### PR TITLE
Add has_distribution functionality for single taxonkey

### PR DESCRIPTION
**Pull request by damianooldoni**
Function `has_distribution` is ready for being tested.

### CODE REVIEW

**Comment by damianooldoni** [comment]
Thanks @peterdesmet  for finding this bug! 
Behavior function `has_distribution` has been improved, based on your review (see  https://github.com/trias-project/trias/pull/6/commits/6164c2e5628c9bd964a32d8329d9ece4b85808ec)
I added your example in test file `test_output_has_distribution.r` together with its opposite, a taxa which has no distribution and therefore, it should return `FALSE`, no matter user property parameters. See https://github.com/trias-project/trias/pull/6/commits/8e4b8ef492409ddd8e6a98185b024fa699c8637f

**Comment by peterdesmet** [comment]
Great. Meanwhile, a feature request for this function: #8

**Comment by peterdesmet** [comment]
Another bug: #9 😄

**Comment by peterdesmet** [comment]
With #9 fixed, I'm accepting this PR.

**Pull request merged**
