### PR TITLE
Add gbif verify synonyms

### PR DESCRIPTION
**Pull request by damianooldoni**
Implementation of function `gbif_verify_synonyms()` as requested in  trias-project/unified-checklist#2. 
In documentation an example of how the function should work is added. In such example two dataframes are built, `taxa_in` and `verified_synonyms_in`. They contain the same data as files [taxa.tsv](https://github.com/trias-project/unified-checklist/blob/get-taxa-verify-synonyms/data/input/taxa.tsv) and [verified_synonyms.tsv](https://github.com/trias-project/unified-checklist/blob/get-taxa-verify-synonyms/data/input/verified_synonyms.tsv).

### CODE REVIEW

**Comment by peterdesmet** [comment]
Looking good! Functionality is as asked. 👍 A couple of new thoughts:

## 1. accepted taxa

I would like better handling of accepted taxa:

```r
taxa_in <- data.frame(
  backbone_taxonKey = c(2360181, 2427092, 2651108, 5228676),
  backbone_scientificName = c("Aspius aspius (Linnaeus, 1758)",
                              "Rana catesbeiana Shaw, 1802",
                              "Polystichum tsus-simense (Hook.) J.Sm.",
                              "Apus apus (Linnaeus, 1758)"),
  backbone_acceptedKey = c(5851603, 2427091, 4046493, 5228676),
  backbone_accepted = c("Leuciscus aspius (Linnaeus, 1758)",
                       "Lithobates catesbeianus (Shaw, 1802)",
                       "Polystichum luctuosum (Kunze) Moore.",
                       "Apus apus (Linnaeus, 1758)"),
  stringsAsFactors = FALSE)
```

This example will add `Apus Apus` to `verified_synonyms` while it is an accepted taxon (and thus useless to verify). Records in taxa where `backbone_taxonKey` = `backbone_acceptedKey` should be **ignored**. Note: if a taxon was previously a synonym, but now an accepted taxon (same keys), then its verified synonym will end up in `unused_synonyms`, which is perfect.

Update the example with info above.

## 2. No call to GBIF

Currently, there is a call to GBIF to add the kingdom to `verified_synonyms`. I would simplify the function and not make any calls to GBIF, i.e. no new information is called. That means we won't populate `kingdom`: for now, let's remove it as a required column (and remove it from the example). If that gets too annoying, we could always populate it from `taxa`.

Since we're not making a call to gbif, I'd actually name the function `verify_synonyms` to be very clear about that.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet ! Your thoughts make totally sense. I will translate them in code.

**Comment by peterdesmet** [comment]
As discussed, update function to in first step filter data frame on:

    backbone_acceptedKey != NA  AND backbone_acceptedKey != backbone_taxonKey

That way we only check synonyms.

However, as it might _maybe_ happen that a synonym has an `acceptedKey = NA`, I would **instead** add an extra column as a parameter to the function: `backbone_taxonomicStatus`. That we can just filter:

    backbone_taxonomicStatus = "SYNONYM"

Which is also more readable

**Comment by damianooldoni** [comment]
@peterdesmet, I think I got it. 
Tests and example in function documentation use example provided in https://github.com/trias-project/trias/pull/15#issuecomment-380366552.
In particular, `backbone_taxonomicStatus` column has been added among the columns of `taxa` and its presence is compulsory. By joining, `verified_synonyms` is present in `output$verified_synonyms`, `output$unused_synonyms`  and `output$new_synonyms` as well.
Column `backbone_kingdom` has been removed and its presence is not checked anymore.

**Comment by damianooldoni** [comment]
Meanwhile the goal of this function is changed, I think. Based on discussion about unified checklist, this function should:

1. check synonyms (more or less as the function already does)
2. check taxa with no match to GBIF backbone
3. check taxa with fuzzy match to GbiF backbone

Shouldn't we change the name of the function? I propose `verify_taxa()`. What do you think, @peterdesmet?

**Comment by damianooldoni** [comment]
Thanks @peterdesmet . Still, there is no need to merge. The function changed its specifications but it is still  important. And the branch is quite self-contained. Anyway, I will merge in case I will really need.

**Comment by damianooldoni** [comment]
@peterdesmet : I have just pulled your commit https://github.com/trias-project/trias/commit/87c71d52cfa10db70d66f6ff14e5c668c1825be5 from `master` in this branch. If you think you can find any time to review, I would wait for merging. Otherwise, let's merge it to `master`. And if improvements are needed, we do them in a new branch.

**Pull request merged**
