### PR TITLE
Improve verify taxa

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR tackles issues #28 , #29, #30 and #31 . Tests and documentation updated.
Some small additional changes:
1. all elements of $info are tibble data.frames. No NULL anymore, but empty dataframes in case of no taxa (see https://github.com/trias-project/trias/issues/28#issuecomment-449381454).
2. warning is returned in case some `verifiedBy` are not empty for taxa without `verificationKey`. Such values of `verifiedBy` are removed from `verification`.
3. function `gbif_verify_key()` doesn't throw any error in case a vector of empty characters is given, e.g. `c("", "", "")`. This is useful in case no verification keys are present.
4. for any key not found among all GBIF taxon keys, message `Key _number_ is an invalid GBIF taxon key.` is returned instead of generic rgbif message `Error: Not Found` in `gbif_verify_key()`. Maybe this could be improved at rgbif level in the future.
Note: `gbif_verify_keys()` is used to make `$info$check_verificationKey`.

### CODE REVIEW

**Comment by peterdesmet** [comment]
Have now updated my script in response to new function: https://github.com/trias-project/unified-checklist/commit/505d14979d8ed467ad75ba2dc4fee26ac1b6393e Thanks a lot, makes it easier!

**Comment by damianooldoni** [comment]
Point 1 fixed.

About point 2: the `DONE` refers to **first** step, not second one. If column `verificationkey` is present then you would get this:
```r
Check input dataframes...DONE
Assign verificationKey to taxa which don't need verification...DONE.
```
The sentence `Column verificationKey already exists. It will be overwritten.` is a message thrown while executing the check of input dataframes. For that reason the DONE comes after it. 
Do you still want to remove that `DONE`?

Point 3: it was a defensive programming strategy. I understand it is more annoying for the users. I will implement the cast internally within the function. However, take into account the eventuality that the output dfs columns could have different types than the input dfs' columns.

**Comment by peterdesmet** [comment]
Regarding 2: Then maybe do:

```
Check input dataframes...DONE.
Column verificationKey already exists. It will be overwritten.
```

(but it's a detail really)

Regarding 3: ok

**Comment by damianooldoni** [comment]
Details matter! :+1: 
Point 2 and 3 fixed. See commits above. About point 3: I added (a lot of) `as.character()`, `as.numeric()`, `as.logical()`, `as.Date()` in order to cast all columns of `taxa`and `verification`. Please, check it again.

**Comment by peterdesmet** [comment]
Thanks! Works nicely now.

**Pull request merged**
