### PR TITLE
Fix 84

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR adds data slot to 4 visualization functions as listed in https://github.com/trias-project/trias/issues/84#issuecomment-1172128737.

Note to reviewer (@SanderDevisscher): **This PR should definitively solve #84**. Do not merge/approve the PR until solved, please. Thanks.

Also, it improves assertion checks of input values: `facet_column`, `taxon_names`, `kingdom_names`, `phylum_names`, `first_observed`, `title`, `x_lab`, `y_lab` (length must be 1) and `chosen_pathway_level1` (only for `*_level2` functions). 

Data slots are always returned as **tibble** dataframes.

Update and improve documentation (see #86 among others).

### CODE REVIEW

**Review by SanderDevisscher — COMMENTED** [review]
@damianooldoni to test the data_facet_graph output slot of `visualize_pathways_year_level1` I applied the "family" facet_column but then I got this message prior to getting stuck in a loop `geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?` This makes me expect the message gets created when there's only 1 observation in the data of a given family. 

The same issue can be seen with "order" however the number of "order" groups with only 1 observation is alot fewer than we see in the family groups.  This makes the loop "finite".

**Comment by SanderDevisscher** [comment]
Also I was wondering why kingdom is not an option for facet_column ?

**Comment by damianooldoni** [comment]
Please, @SanderDevisscher, pull the very last commits.
I noticed that using facets automatically returned a plot in "Plot" pane in RStudio. This should not occur, as the plot should be embedded in the returned list. This should be solved now.

Back to the `geom_path` warnings: I don't think we should spend time to remove such warnings. Also, they are returned correctly for each group of data both in the facet as in the top graph.

Try for example this:

```r
protozoa_pathways <- visualize_pathways_year_level1(data, category = "Protozoa", facet_column = "phylum")
```

You get two `geom_path` warnings as you have two plots in two plots (the top graph and the one facet graph) with one point only, impossible to connect by lines. So, for each group of any facet or in the top graph, you will get a warning if only one point exists.

image

Notice also that you get the warning while plotting WITHOUT facet as well (just one of course), but the warning is printed on screen only when you ask for the plot:

```r
# no geom_path warning on console
> protozoa_pathways_no_facet <- visualize_pathways_year_level1(data, category = "Protozoa") 

# geom_path warning returned
> protozoa_pathways_no_facet$plot
geom_path: Each group consists of only one observation. Do you need to adjust
the group aesthetic?
```
While facetting I have to combine top graph and facet graph by `egg::ggarrange(top_graph, facet_graph)` for the `plot` slot and this prints the error on screen immediately.

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
I get the following error when using "kingdom" as facet_column:

```
 Error in `dplyr::distinct()`:
 ! Must use existing variables.
 ✖ `kingdom` not found in `.data`.
```

I check to be sure the kingdom column exists in the data provided to the function and it does. 

Also the graph still plots when not storing the function return in a object.
when I use `test <- visualize_pathways_year_level1(data, facet_column = "family")` it does not plot while when I use `visualize_pathways_year_level1(data, facet_column = "family")` it does. 

PS I used `devtools::install_github("trias-project/trias@fix-84")` to make sure I have the newest version of trias prior to testing

**Comment by damianooldoni** [comment]
@SanderDevisscher: facet kingdom should be implemented in all 4 functions  now. I remember that it was opted to have arg `category` in order to have nice plots for each kingdom/Chordata/Not Chordata as these plots can be arranged at a second stage. But I am happy we can allow faceting on kingdom as well now. It is more flexible.

**Review by SanderDevisscher — APPROVED** [review]

**Comment by SanderDevisscher** [comment]
all my tests work as requested now

**Pull request merged**
