### PR TITLE
R CMD check returns 2 errors

### PR DESCRIPTION
**Pull request by peterdesmet**
I tried to install the new version of the package and ran into an error, so I opened the package repository and did an `R CMD check`:

```
R CMD check results
2 errors  | 1 warning  | 1 note
```

### CODE REVIEW

**Comment by peterdesmet** [comment]
Down to one error:

```
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(trias)
  > 
  > test_check("trias")
  Error in test_check("trias") : could not find function "test_check"
  Execution halted
```

**Comment by peterdesmet** [comment]
It seems all tests should start with `test-` while they are currently `test_` I've update the files, but it doesn't resolve the issue.

**Comment by damianooldoni** [comment]
`R CMD check succeded` after 80e927544f0c16b0ab32920b948dab8c65409877 in `trias@add_gbif_verify_synonyms`. 
@peterdesmet : Can you try R CMD check on `trias@add_gbif_verify_synonyms` and let me know if it is ok on OS X systems as well? Thanks.

**Comment by peterdesmet** [comment]
`trias@add_gbif_verify_synonyms` has since been integrated in master, so I did a R CMD check on the latest master version. Got one error, which I solved in b8fe2c3017d68a3617b7bc54cb50c19369b814ee. Now:

    0 errors | 0 warnings | 2 notes

@damianooldoni I'll let you decide if this branch is still useful or if this PR can be closed without merging.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet . I will close this PR without merging.

**Pull request closed without merging**
