### PR TITLE
Add get taxa function

### PR DESCRIPTION
**Pull request by damianooldoni**

### CODE REVIEW

**Comment by peterdesmet** [comment]
@stijnvanhoey, I added you to @trias-project/rse. Can you review the code of this package and give tips on how to make it more R-esk (the R equivalence of Pythonesk), because that is something I cannot assess.

**Comment by peterdesmet** [comment]
Although nice, the following output is a bit odd:

> No match with GBIF Backbone for 1 taxon keys.

I would return:

> xx taxa found of which yy could not be matched to GBIF backbone.

**Comment by damianooldoni** [comment]
GBIF Match improvements introduced: https://github.com/trias-project/trias/commit/c5e56d1b25e41d22bf9e2ebd3c48d9590f5a49f6 and https://github.com/trias-project/trias/commit/2f23e67a47dba5da28fbd6ac60dea037c1d33e67
I modified the other message option too:

> All taxa match GBIF backbone.

changed:

> All xx taxa match GBIF backbone.

**Comment by peterdesmet** [comment]
I'm getting:

    Error in checklist_taxa %<>% ungroup : could not find function "%<>%"

Is dplyr een dependency van trias?

**Comment by peterdesmet** [comment]
Bug is solved with:

    library(magrittr)

Odd, I thought this was a dependency of dplyr already... best to look into this and make it a dependency of the package... or write that code differently.

**Comment by damianooldoni** [comment]
Yes, you are right: dependencies in file `DESCRIPTION` were not updated! Bug solved in c59961d9d396c2b90691ffa7848ffa8c9c0b58df

**Pull request merged**
