### PR TITLE
93 errors while running climate matching

### LINKED ISSUE #93: Errors while running climate matching
This line of code is the probable cause of the error below: https://github.com/trias-project/trias/blob/6c1dc31e5aa7ff9e1e3b89adc75c7f3e127ca4af/R/climate_match.R#L167

> Error in if (length(taxon_key) == 1 & is.na(taxon_key)) { : 
>   the condition has length > 1

this is an other error I get:

> Error:
> ! Can't subset `.data` outside of a data mask context.

the error only occurs when `maps == TRUE`
this is the `rlang::last_error()` printout:

> Backtrace:
>   1. trias::climate_match(...)
>  21. leaflet::addCircleMarkers(...)
>  24. leaflet::invokeMethod(...)
>  25. leaflet::evalFormula(list(...), data)
>  26. leaflet evalAll(list)
>  27. base::lapply(x, evalAll)
>  28. leaflet FUN(X[[i]], ...)
>  29. leaflet:::resolveFormula(x, data)
>  30. [ base::eval(...) ] with 1 more call
> Run `rlang::last_trace()` to see the full context.

and the last_trace:

>   1. ├─trias::climate_match(...)
>   2. │ └─... %>% ... at trias/R/climate_match.R:491:4
>   3. ├─leaflet::addPolygons(., data = sea, fillColor = "#e0e0e0", weight = 0.5)
>   4. │ ├─... %>% expandLimitsBbox(pgons)
>   5. │ └─leaflet::invokeMethod(...)
>   6. │   └─leaflet::dispatch(...)
>   7. ├─leaflet::expandLimitsBbox(., pgons)
>   8. │ └─leaflet::expandLimits(map, bbox[2, ], bbox[1, ])
>   9. ├─leaflet::addLayersControl(., baseGroups = ~.data$acceptedScientificName)
>  10. │ ├─leaflet::invokeMethod(...)
>  11. │ │ └─crosstalk::is.SharedData(data)
>  12. │ └─leaflet::getMapData(map)
>  13. ├─leaflet::addLegend(...)
>  14. │ ├─leaflet::invokeMethod(map, data, "addLegend", legend)
>  15. │ │ └─crosstalk::is.SharedData(data)
>  16. │ └─leaflet::getMapData(map)
>  17. ├─leaflet::addLegend(...)
>  18. │ ├─leaflet::invokeMethod(map, data, "addLegend", legend)
>  19. │ │ └─crosstalk::is.SharedData(data)
>  20. │ └─leaflet::getMapData(map)
>  21. ├─leaflet::addCircleMarkers(...)
>  22. │ ├─... %>% expandLimits(pts$lat, pts$lng)
>  23. │ └─leaflet::invokeMethod(...)
>  24. │   └─leaflet::evalFormula(list(...), data)
>  25. │     └─leaflet evalAll(list)
>  26. │       └─base::lapply(x, evalAll)
>  27. │         └─leaflet FUN(X[[i]], ...)
>  28. │           └─leaflet:::resolveFormula(x, data)
>  29. │             └─base::eval(f[[2]], metaData(data), environment(f))
>  30. │               └─base::eval(f[[2]], metaData(data), environment(f))
>  31. │                 ├─acceptedScientificName
>  32. │                 └─rlang:::`$.rlang_fake_data_pronoun`(.data, acceptedScientificName) #=> **suspected cause of error**
>  33. │                   └─rlang:::stop_fake_data_subset(call)
>  34. │                     └─rlang::abort(...)
>  35. └─leaflet::expandLimits(., pts$lat, pts$lng)

### PR DESCRIPTION
**Pull request by SanderDevisscher**
Fixes #93 

Both initial errors have been fixed. 
Additionally I swapped most of the `sp` code for `sf`, however not all yet due to time constraints. 
I also added some logic to cut big datasets (species with many observations) into workable subsets including some cleanup in between. This also allowed me to add some progress feedback in the form of progress bars. 

I've allready run `devtools::document()`.

### CODE REVIEW

**Review by damianooldoni — COMMENTED** [review]
Nice work, @SanderDevisscher! 
I added sf to the dependencies and bumped the version number.
Still, I see that you use @importFrom syntax in ROxygen: it's difficult to maintain the list of functions to import and it's alway a mess 😄 So, as you can see in many other trias functions and also in many other oscibio packages, we are moving towards a consistent use of `pkg::func_name()` in the code. This saves a lot of maintenance work.
I will do this and fix other check errors. If they are related to your code, I will contact you, @SanderDevisscher : is it ok for you?

**Comment by SanderDevisscher** [comment]
> Nice work, @SanderDevisscher! I added sf to the dependencies and bumped the version number. Still, I see that you use @importFrom syntax in ROxygen: it's difficult to maintain the list of functions to import and it's alway a mess 😄 So, as you can see in many other trias functions and also in many other oscibio packages, we are moving towards a consistent use of `pkg::func_name()` in the code. This saves a lot of maintenance work. I will do this and fix other check errors. If they are related to your code, I will contact you, @SanderDevisscher : is it ok for you?

Damn I just removed all `sf::`

Also ok for me

**Review by damianooldoni — APPROVED** [review]
@SanderDevisscher: I approve my own changes 🤣 
I would like to invert our roles now and putting you as official reviewer but of course it's not possible as you submitted this PR.
However, could you please double check that `climate_match()` function works as expected?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher: I approve my own changes 🤣 I would like to invert our roles now and putting you as official reviewer but of course it's not possible as you submitted this PR. However, could you please double check that `climate_match()` function works as expected?

🤣
I'll check if everything still works

**Comment by SanderDevisscher** [comment]
@damianooldoni I checked the function. Besides 2 missing `sp::` everything was like it should be. 

I'm merging the PR now!

**Pull request merged**
